os: linux
dist: bionic

language: ruby
rvm: 3.0.0

cache: bundler

addons:
  apt:
    packages:
      - libcurl4-openssl-dev # required to avoid SSL error (for htmlproofer)

before_script:
- chmod +x ./script/cibuild

script: "./script/cibuild"

branches:
  only: main

git:
  depth: false # for posts lastmod

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
