os: linux
dist: bionic

language: ruby
rvm: 3.0.0

cache: bundler

addons:
  apt:
    packages:
      - libcurl4-openssl-dev # required to avoid SSL error (for htmlproofer)

script:
  - git -C "$HOME" clone "$BUILDER_REPO" --depth=1 -q
  - eval "$BUILD_CMD"

branches:
  only: main

git:
  depth: false # for posts lastmod

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
